---
- name: Download Jetbrains Toolbox
  ansible.builtin.unarchive:
    src: 'https://download-cdn.jetbrains.com/toolbox/jetbrains-toolbox-1.21.9712.tar.gz'
    remote_src: yes
    dest: '/tmp'

- name: Create JetBrains Toolbox dir
  ansible.builtin.file:
    path: '/home/jlh/.local/share/JetBrains/Toolbox/bin'
    state: directory
    owner: jlh
    group: jlh

- name: Install Jetbrains Toolbox binary
  ansible.builtin.copy:
    src: '/tmp/jetbrains-toolbox-1.21.9712/jetbrains-toolbox'
    dest: '/home/jlh/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox'
    owner: jlh
    group: jlh
    mode: '755'

- name: Install Jetbrains .desktop
  ansible.builtin.copy:
    content: |
      [Desktop Entry]
      Icon=/home/jlh/.local/share/JetBrains/Toolbox/toolbox.svg
      Exec=/home/jlh/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox %u
      Version=1.0
      Type=Application
      Categories=Development
      Name=JetBrains Toolbox
      StartupWMClass=jetbrains-toolbox
      Terminal=false
      MimeType=x-scheme-handler/jetbrains;
      X-GNOME-Autostart-enabled=true
      StartupNotify=false
      X-GNOME-Autostart-Delay=10
      X-MATE-Autostart-Delay=10
      X-KDE-autostart-after=panel
    dest: /home/jlh/.local/share/applications/jetbrains-toolbox.desktop
    force: no
    owner: jlh
    group: jlh
    mode: '755'
