---
- name: Add libvirt group
  ansible.builtin.group:
    name: libvirt
    state: present

- name: Set groups
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - wheel
      - libvirt
      - wireshark
  loop:
    - jlh
    - justin
