---
- name: Install Minikube KVM deps
  ansible.builtin.dnf:
    name: '@virtualization'
    state: latest

- name: Install kubernetes repo
  ansible.builtin.copy:
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubectl
  ansible.builtin.dnf:
    name: 'kubectl'
    state: latest

- name: Install Minikube
  ansible.builtin.dnf:
    name: 'https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm'
    disable_gpg_check: yes
    state: present
