---
- name: Enable Flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    
- name: Install Gedit
  flatpak:
    name: org.gnome.gedit
    state: present

- name: Install Spotify
  flatpak:
    name: com.spotify.Client
    state: present

